name: Deploy

# Trigger the workflow on push and
# pull request events on the master branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          - name: Setup Nodejs and npm
            uses: actions/setup-node@v4
            with:
              node-version: "16"

          - name: Setup yarn
            run: npm install -g yarn

          - name: Setup Nodejs with yarn caching
            uses: actions/setup-node@v4
            with:
              node-version: "16"
              cache: yarn

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/Invoice-generator && ./.scripts/deploy.sh
            whoami
            ls -al
