name: Deploy

# Trigger the workflow on push and
# pull request events on the master branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: Setup Yarn
        with:
          node-version: "16"
          cache: "yarn"
      - run: corepack enable
      - run: yarn install
      - run: yarn lint
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/Invoice-generator && ./.scripts/deploy.sh
            whoami
            ls -al
